name: your_journal
description: "A Flutter Journal project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.10
  table_calendar: ^3.2.0
  intl: ^0.20.1
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2
  cloud_firestore: ^5.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/book.png
    - assets/images/icon.jpg
    - assets/images/mountain.jpg
    - assets/images/peakpx.jpg
    - assets/images/purple.jpg
    - assets/images/splash.png


fonts:
    - family: Italianno
      fonts:
        - asset: assets/fonts/Italianno-Regular.ttf

