// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu54ungIq8XxBNlIg46LsiE9JXh-_gfmo',
    appId: '1:855503520879:web:1deaab9eab7f354cb9799a',
    messagingSenderId: '855503520879',
    projectId: 'your-journal-b7fcf',
    authDomain: 'your-journal-b7fcf.firebaseapp.com',
    storageBucket: 'your-journal-b7fcf.firebasestorage.app',
    measurementId: 'G-SWMQ958460',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWyVjVItYSZl7a8-QMuEGO7-ZsModK4cY',
    appId: '1:855503520879:android:b2495721ef71f6a9b9799a',
    messagingSenderId: '855503520879',
    projectId: 'your-journal-b7fcf',
    storageBucket: 'your-journal-b7fcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6XXODpQ4YpAKXKmkyitQPrI_jlgccFrE',
    appId: '1:855503520879:ios:1dda5082b5aec917b9799a',
    messagingSenderId: '855503520879',
    projectId: 'your-journal-b7fcf',
    storageBucket: 'your-journal-b7fcf.firebasestorage.app',
    iosClientId:
        '855503520879-jk85fhbovh71s7hvlpjn70d1o9k7lggp.apps.googleusercontent.com',
    iosBundleId: 'com.binus.yourjournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6XXODpQ4YpAKXKmkyitQPrI_jlgccFrE',
    appId: '1:855503520879:ios:1dda5082b5aec917b9799a',
    messagingSenderId: '855503520879',
    projectId: 'your-journal-b7fcf',
    storageBucket: 'your-journal-b7fcf.firebasestorage.app',
    iosClientId:
        '855503520879-jk85fhbovh71s7hvlpjn70d1o9k7lggp.apps.googleusercontent.com',
    iosBundleId: 'com.binus.yourjournal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu54ungIq8XxBNlIg46LsiE9JXh-_gfmo',
    appId: '1:855503520879:web:1deaab9eab7f354cb9799a',
    messagingSenderId: '855503520879',
    projectId: 'your-journal-b7fcf',
    authDomain: 'your-journal-b7fcf.firebaseapp.com',
    storageBucket: 'your-journal-b7fcf.firebasestorage.app',
    measurementId: 'G-SWMQ958460',
  );
}
